---
permalink:   /:categories/:title
exclude: [Gemfile, Gemfile.lock, config.rb]
markdown: redcarpet
redirects: yes
tag_page_layout: tag_page
tag_page_dir: tags
highlighter: 'rouge'
asset_url:
  - production: /assets
  - local: /assets
