source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-cdn'
gem 's3_website'
gem 'jekyll-redirects'
gem 'jekyll-tagging'
gem 'kramdown'
gem 'foreman'
gem 'rerun'
gem 'sass'
gem 'bourbon'
gem 'neat'
gem 'bitters'
